export const slides = {
  'Présentation': [
    { title: 'Présentation', image: '/slides/presentation.png' },
  ],
  'Échauffement': [
    { title: "Échauffement"},
    { title: "En quelle année l’équipe Stan Robotix a-t-elle été créée ?"},
    { title: 'Bonus : quelle est la date exacte ?'},
    { title: 'Qui sont les capitaines de la première année ?'},
    { title: 'Qui sont les capitaines cette année ?'},
    { title: 'Quel est le numéro et le nom de l’équipe québécoise possédant les mêmes chiffres que Stan Robotix ?'},
    { title:'', image: '/slides/2626.jpg'},
    { title: 'Imiter le son du début d’un match.'},
    { title: '', media: {type: 'audio', src: '/blindtest/teleop.mp3'}},
    { title: 'Quel mentor n’a (honteusement) jamais acheté de tasse Stan Robotix ?'},
    { title: 'En quelles années le festival de robotique régional ne s’est pas tenu à Montréal ?'},
    { title: 'Comment s’appelle cette danse ?', media: {type: 'video', src: '/slides/tixdansen.mp4'} },
    { title: 'Sur les 13 compétitions auxquelles Stan Robotix a participé, Betabot et FRC confondues, combien ont été gagnées ?'},
    { title: '', image: '/slides/2022memes.png'}
  ],
  'L\'atelier': [
    { title: "L'atelier, ma deuxième maison" },
    { title: 'Quel est le numéro de la salle de l’atelier ?'},
    { title: 'Quel est le code du cadenas de l’armoire de la M109 ?'},
    { title: 'Sur le poster Disney de l’atelier, un nom est inscrit sur chaque princesse. Donner un nom et sa princesse.'},
    { title: 'Quels sont les 5 états de batterie indiqués sur l’armoire des ordinateurs ?'},
    { title: 'De quelle franchise provient ce jouet ?', image: '/atelier/poney.png' },
    { title: 'Quel personnage de film à été imprimé en 3D avec la tête de Dwayne Johnson (The rock) dessus ?'},
    { title: 'Sur l’affiche bleu ciel présentant le club, comment est orthographié Stan Robotix ?'},
    { title: 'Sur quel média peut-on voir cette photo ?', image: '/atelier/derek.png' },
    { title: 'Quel capitaine ou co-capitaine n\'apparait sur aucune photo dans l\'atelier ?', image: '/atelier/derek.png' },
],
  'Lore très (très) obscur': [
    { title: 'Lore très (très) obscur', image: '/lore/lore.png' },
    { title: 'À quoi fais-je référence ?'},
    { title: 'Nommer une relique datant d\'au moins de 2019.', image: '/lore/relique.png'},
    { title: 'Qui est, par défaut, le chef sécurité ?'},
    { title: 'À quoi correspondent « le Français » et « le communiste » ?'},
    { title: 'Pourquoi est-ce que Stan Robotix se transforme en maison de retraite ?', image:'/lore/mentors.png'},
    { title: 'Quel capitaine à déjà volé lors d’un Gala ?'},
    { title: 'Preuve :', image: '/lore/philippe.png'},
    { title: 'Dans ses premières années, Stan Robotix aurait pu se convertir en club de fitness car un objet important était manquant ou se brisait souvent. Lequel ?'},
    { title: 'Sur ce diagramme, où se situe le régime politique Robotixien ?', image: '/lore/chart.png' },
    { title: 'Compléter les termes suivants : Gros [...].pdf, Vidéo Epic (fou [...]).pdf, Build the [...] Indice : Joshua'},
    { title: 'Selon la légende, les problèmes de communications avec le robot lors des compétitions sont dus à qui ?'}

  ],

  '« Contexte ? »': [
    { title: '« Contexte ? »', image: '/contexte/no3000.png' },
    { title: '', image: '/contexte/simone.png' },
    { title: '', image: '/contexte/maxvictor.png' },
    { title: '', image: '/contexte/batterie.png' },
    { title: '', image: '/contexte/coke.png' },
    { title: '', image: '/contexte/kalo.png' },
    { title: '', image: '/contexte/rio.png' },
    { title: '', media: {type: 'video', src: '/contexte/2021.mov'}},
    { title: '', image: '/contexte/squishy.png' },
    { title: '', image: '/contexte/inspecteurs.png' },
    { title: '', media: {type: 'video', src: '/contexte/daminecrashout.mp4'} },
  ],

  'Trucs aléatoires': [
    { title: 'Trucs aléatoires', image: '/slides/IWANTYOU.png' },
    { title: 'Quelle est la police d\'écriture de Stan Robotix parmi : Good Times, Nasalization, Ethnocentric, Conthrax et Nulshock ?'},
    { title: '', image:'/font/nasalization.png'},
    { title: '', image:'/font/ethnocentric.png'},
    { title: '', image:'/font/conthrax.png'},
    { title: '', image:'/font/nulshock.png'},
    { title: '', image:'/font/goodtimes.png'},
    { title: 'Donner, dans l’ordre, tous les capitaines / co-capitaines de l’équipe.'},
    { title: 'Quelle activité parascolaire les membres de Robotix choisissent-ils davantage ?'},
    { title: 'Combien de sites Stan Robotix sont actifs ?'},
    { title: 'Quels sont, de gauche à droite, les symboles du logo de FIRST ?'},
    { title: 'Quelle entreprise est notre plus fidèle sponsor ?'},
    { title: 'Quelle disposition de panneau électrique, parmi : un panneau vertical faisant face à l’extérieur, un panneau qui tombe au sol, un panneau vertical en deux couches, un panneau divisé en trois et caché par des mécanismes ou un panneau sous une rampe n\'a JAMAIS été mise sur un robot de compétition ?'},
    { title: 'Quelle(s) sous-équipe(s) change(nt) de nom presque chaque année ?'},
    { title: '2016-2017', image:'/marketing/2016.png'},
    { title: '2017-2018', image:'/marketing/2017.png'},
    { title: '2018-2019', image:'/marketing/2018_am.png'},
    { title: '2018-2019', image:'/marketing/2018_m.png'},
    { title: '2019-2020', image:'/marketing/2019.jpg'},
    { title: '2020-2021', image:'/marketing/2020.png'},
    { title: '2021-2022', image:'/marketing/2021.png'},
    { title: '2022-2023', image:'/marketing/2022.png'},
    { title: '2022-2023', image:'/marketing/skaloyan.png'},
    { title: '2023-2024', image:'/marketing/2023.png'},
    { title: '2024-2025\n Marketing = inexistant',},
    { title: '2025-2026', image:'/marketing/2025.png'},
    { title: '2025-2026', image:'/marketing/2025_erreur.png'},
    { title: '2026-2027', image:'/marketing/2026_erreur.png'},
    { title: 'Le système international comporte 7 unités de mesure. Donner au moins deux unités de remplacement purement robotixienne.'},
    { title: 'Donner au moins 5 noms de roues utilisées dans un robot.'}
  ],

  'Pour les vieux': [
    { title: 'Pour les vieux', image: '/lore/capitaines.png' },
    { title: 'Donner le nombre de versions DIFFÉRENTES du t-shirt Stan Robotix qui existaient la 2e année.'},
    { title: '', image: '/slides/tshirts.png'},
    { title: 'Durant la compétition Deep Space, comment s’est gagné l’unique match victorieux de Stan Robotix ?'},
    { title: 'Avant Polytechnique, où se faisait le kickoff au Québec ?'},
    { title: 'Depuis 2016, combien de mécanismes de lanceur (de balles) par moteur ont été montés sur un robot pour la compétition FIRST ?'},
    { title: 'Durant l’année 2020-2021, l’activité a été en partie mise sur pause. Combien de nouveaux élèves ont rejoint cette année-là ?'},
    { title: 'Quel est le record d’années de suite où il y a eu un / une chef design chaque année.', image: '/slides/ronnie.png'},
    { title: 'Parmi les pilotes de Stan Robotix aux compétitions FIRST, combien n’ont JAMAIS fait partie de l’équipe programmation ?'},
    { title: 'Avant le dernier match de la finale de la compétition FIRST de 2022, quel composant a dû être remplacé après une inspection ?'},
    { title: 'Explication', image: '/slides/pdp.gif'},
    { title: 'Quel matériau insolite a servi à fabriquer les bumpers de la compétition Betabot 2016 ?'},
    { title: 'Preuve', image: '/slides/jeans.jpg'},
    { title: 'Avant l’existence de l’atelier, où travaillait l’équipe pour construire le robot ?'},
  ],

  'Si tu as plus de 20 ans, oublie': [
    { title: 'Si tu as plus de 20 ans, oublie', media: {type: 'video', src: '/slides/roomtour.mp4'} },
    { title: 'Comment s’appelait la dernière compétition FIRST ?' },
    { title: 'Quel est le nouveau nom du « Dean’s List Award » ?' },
    { title: 'Combien de jours a-t-il fallu avant que le compte Stan Robotix n’obtienne son premier copyright strike dû aux lives YouTube ?' },
    { title: 'Quelle game piece a été éventrée pour un mécanisme ?' },
    { title: 'Preuve :', media: {type: 'video', src: '/slides/algae.mp4'} },
    { title: 'Comment s’appelle cet animal ?', image: '/slides/cetacier.png' },
    { title: 'Quel programme de FIRST va disparaître l’année prochaine ?' },
    { title: 'Quel est le dernier prix remporté par Stan Robotix ?' },
    { title: 'Quel composant remplacera le RoborIO ?' },
    { title: 'L’année passée, en quelle position a terminé Stan Robotix à la fin de la phase de qualification ?' },
    { title: 'Donner les noms des deux derniers robots.'},
  ],

  'Rivalité construction / programmation': [
    { title: 'Rivalité construction / programmation', image: '/slides/control.png' },
    { title: 'Citer 5 chefs de construction.'},
    { title: 'À quoi correspondent les termes 3/8 et 4mm ?'},
    { title: 'Expliquer la différence entre une vis, un écrou et un boulon.', image: '/slides/simomeme.png'},
    { title: 'Quelle est la différence entre l’acrylique et le polycarbonate ?'},
    { title: 'Compléter les deux branches vides.', image: '/slides/flowchart.png'},
    { title: 'Réponse', image: '/slides/flowchart2.png'},
    { title: 'Citer 5 chefs de programmation.'},
    { title: 'Quel logiciel utilisé de 2019 à 2022 a été à l’origine de la pandémie de Covid-19 ?'},
    { title: 'Si je souhaite me faire cuire un œuf, sur quel composant dois-je le mettre ?'},
    { title: 'Quel mot de passe constitué uniquement de chiffres, mais pas 6622, était utilisé il y a longtemps sur les laptops ?'},
    { title: 'En Command-Based, la classe RobotContainer permet de lier des commandes à une manette. Quel est son ancien nom d’avant la mise à jour de 2021-2022 ?'},
  ],

  'Blindtest': [
    { title: 'Blindtest', image: '/blindtest/simone.png' },
    { title: '', media: {type: 'audio', src: '/blindtest/fin.mp3'}},
    { title: '', media: {type: 'audio', src: '/blindtest/deepspace.mp3'}},
    { title: '', media: {type: 'audio', src: '/blindtest/crescendo.mp3'}},
    { title: '', media: {type: 'audio', src: '/blindtest/dive.mp3'}},
    { title: '', media: {type: 'audio', src: '/blindtest/rebuilt.mp3'}},
    { title: '', media: {type: 'audio', src: '/blindtest/promo.mp3'}},
    { title: '', media: {type: 'video', src: '/blindtest/promo.mp4'}},
    { title: '', media: {type: 'audio', src: '/blindtest/timeless.mp3'}},
  ],

  'GP Explorer': [
    { title: 'GP Explorer (FRC et Betabot)', image: '/gp/churro.png' },
    { title: '', image: '/gp/cone.png'},
    { title: '', image: '/gp/gear.png'},
    { title: '', image: '/gp/rings.png'},
    { title: '', image: '/gp/cubes.png'},
    { title: '', image: '/gp/cylinders.png'},
    { title: '', image: '/gp/gear.png'},
    { title: '', image: '/gp/balls.png'},
    { title: '', image: '/gp/bag.png'},
  ],

  'Quiz des équipes FRC au Québec': [
    { title: 'Quiz des équipes FRC au Québec', image: '/equipes/equipe.jpg' },
    { title: '', image: '/equipes/cuivreetor.png'},
    { title: '', image: '/equipes/expresso.png'},
    { title: '', image: '/equipes/spartiates.png'},
    { title: '', image: '/equipes/northemknights.png'},
    { title: '', image: '/equipes/pls.png'},
    { title: '', image: '/equipes/rikitik.png'},
    { title: '', image: '/equipes/patenteux.png'},
    { title: '', image: '/equipes/westtechpaladins.png'},
    { title: '', image: '/equipes/tech4kids.png'},
    { title: '', image: '/equipes/dynamique.png'},
  ],

 'Fou de compétitions FRC': [
    { title: 'Fou de compétitions FRC', image: '/slides/gouello.jpg' },
    { title: 'À quoi servent les deux boutons dans la zone des pilotes, sur le terrain ?'},
    { title: 'Lors de quelle compétition y-avait-il des joueurs humains sur le terrain pendant le match ?'},
    { title: 'Comment s’appelle la mascotte de Robotique First Québec ?'},
    { title: 'Blip', image: '/frc/blip.png'},
    { title: 'À 30 points près, quel est le record absolu de points marqués lors d’une compétition, toutes saisons et régions confondues ?'},
    { title: 'Plainfield District Event', image: '/frc/score.png'},
    { title: 'Quelle est la différence entre les casquettes jaunes et les casquettes oranges ?', image: '' },
    { title: 'Nommer 4 des 8 divisions au FIRST Championship ?'},
    { title: 'Il est possible de contrôler le robot avec plusieurs appareils / manettes. Quelle règle principale doivent-ils respecter ?'},
    { title: 'Quelle est la différence entre le système de compétition par District et par Regional ?'},
    { title: 'Avant de se dérouler à Houston mais après St. Louis, où se passait le FIRST Championship ?'},
    { title: 'Combien d’écussons sont distribués à chaque équipe lorsqu’elles arrivent sur le site de la compétition ?', image: '/frc/pin.png' },
  ],


  '« Alors comme ça tu aimes les robots ? »': [
    { title: '« Alors comme ça tu aimes les robots ? »', image: '/robots/wow.png'},
    { title:'', image: '/robots/2020frc.png'},
    { title:'', image: '/robots/2019frc.png'},
    { title:'', image: '/robots/2017frc.png'},
    { title:'', image: '/robots/2021betabot.png'},
    { title:'', image: '/robots/2022frc.png'},
    { title:'', image: '/robots/2026frc.png'},
    { title:'', image: '/robots/2019betabot.png'},
    { title:'', image: '/robots/2025frc.png'},
    { title:'', image: '/robots/2017betabot.png'},
    { title:'', image: '/robots/2018frc.png'},
  ]

  ,

  'Questions de K-Lité': [
    { title: 'Questions de K-Lité', image: '/slides/chart.png' },
    { title: 'Donner la nature de l\'incident diplomatique.', image: '/slides/incidentdiplomatique.jpg' },
    { title: 'Donner, à 5%, près, le taux d’inflation du prix de l’activité entre 2016-2017 et 2026-2027'},
    { title: 'Quelle salle a eu une de ses vitres brisée par un robot ?'},
    { title: 'A combien de représentants du SVE différents a été confronté Stan Robotix depuis 10 ans (à un près) ?'},
    { title: 'Combien de trophées ont été brisés ?'},
    { title: 'Combien, à 500$ près, doit l’association étudiante à Stan Robotix ?'},
    { title: 'Entre Alexandre, Emmanuelle, Alice, Kaloyan, Stéphanie et moi, qui a envoyé le plus de message sur Discord ?'},
    { title: 'En 2026, 25 élèves se sont présentés à la compétition. Combien de mentors sont venus (pas forcément en même temps) ?'},
  ]
}

export const categories = Object.keys(slides).filter((category) => slides[category].length > 0)
export const defaultCategory = categories[0]